### ISSUE TITLE
does godef support find symbols defined in golang's vendor directory?

### ISSUE THREAD

**Issue by redhatlinux10** [rogpeppe/godef#39]
godef version : 93a5898bcbd891dafa723f8d6d44eb5e9dd96786
os : windows 7 32bit

i am using `visual studio code` + `lukehoban's go language support` + `godef`,

`godef` can find definitions from my own codebase and `GOPATH`, but can not find definitions from `vendor` directory within codebase's root directory.

**Comment by rogpeppe** [comment]
Can you be more specific please? What file were you in when trying to find the definition? What symbol did you try? Ideally I'd like to see the exact source code you were trying and the arguments passed to godef.

**Comment by rogpeppe** [comment]
Marking this as invalid because vendor directories inside the root are not
supported by Go at all. Godef is just using the standard Go import logic here.

See my reply on https://github.com/Microsoft/vscode-go/issues/320

Please comment again if you feel that this issue is still valid, and I'll reopen it.
