### ISSUE TITLE
Symbolic link problem

### ISSUE THREAD

**Issue by JianleiZhang** [rogpeppe/godef#76]
godef currently supports vendor. But when the src in $GOPATH is linked by a symbolic link, godef does not work.

**Comment by jguenther** [comment]
I don't think this is a problem iwth godef--symlinks inside `$GOPATH` don't work well in general with built-in go tools in my experience.

Instead of making `$GOPATH/src/github.com/blah/blah` a symlink to e.g. `$HOME/code/blah`, move the actual code dir to your gopath, and make `$HOME/code/blah` a symlink to `$GOPATH/src/github.com/blah/blah` instead. That should work.

**Comment by JianleiZhang** [comment]
Thanks for your reminder, I know what to do.
