### ISSUE TITLE
Jump to definition of a specific implementation of interface functions

### ISSUE THREAD

**Issue by abourget** [rogpeppe/godef#8]
Often I want to debug an interface, but I'm really debugging one of its implementations..

When I look at code that calls funcs on that interface, and I jump to definition, I jump to the type definition.. Would it be possible to drop somewhere a file, or annotate with some comments for temporary indirection of jumps to that interface, to a specific implementation instead ?

Ex:

```
type Plugin interface {
    Boo()
}

type Plugin1 struct {}
func (p *Plugin1) Boo() {}

func main() {
    plugplug := Plugin(&Plugin1{})
    plugplug.Boo()
}
```

Attempting to jump to `Boo`'s definition, we get to the `Plugin` interface.  I'd like to jump to `Plugin1`'s `Boo()` instead.. since I'm working on that one.

Could it have something like:

```
// godef: Plugin1
//  or
// godef: otherpkg.Plugin1
//  or
// godef: github.com/bob/dylan:Plugin1
//  or something ?
type Plugin interface{
   ...
```

that'd be so awesome!

thanks

**Comment by jsdir** [comment]
:+1: This would be epic.

**Comment by rogpeppe** [comment]
In general this requires more intelligence than godef can supply.
The more general purpose (and totally awesome)  [guru tool](https://godoc.org/golang.org/x/tools/cmd/guru) can do this.

That tool can also jump to definitions like godef can, but it's
much much slower (30-50x) in many cases, which is why godef continues
to exist.
